### ISSUE TITLE
collectm is killing collectd concentrator

### ISSUE THREAD

**Issue by nathanwebb** [perfwatcher/collectm#18]
Hi,

I have collectm setup and sending to a collectd concentrator, which mostly works fine, but recently I've started experiencing high CPU utilisation on the collectd concentrator, and the collectm data stops being received. I only have collectm clients sending to the collectd network plugin.

Syslog is filling up with:

```
Aug 12 12:21:57 app1 collectd[1371]: network plugin: parse_packet: Received truncated packet, try increasing `MaxPacketSize'
Aug 12 12:21:57 app1 collectd[1371]: network plugin: parse_packet: Received truncated packet, try increasing `MaxPacketSize'
Aug 12 12:21:57 app1 collectd[1371]: network plugin: parse_part_string: Output buffer too small.
Aug 12 12:21:57 app1 collectd[1371]: plugin_dispatch_values: Dataset not found: nbcpu (from "LMSSYDCW1/cpu-total/nbcpu"), check your types.db!
```

I have increased MaxPacketSize in the collectd config to 65535 but that hasn't made any difference.

Does anyone have any thoughts on this?

**Comment by feraudet** [comment]
Hi,

It's due to 2 bugs:
- First in collectm who fill packet with extra zero until MaxPacketSize
- Second in collectd who mishandle bad packet format

Here more details : https://github.com/astro/node-collectdout/issues/10

I'will bump collectdout to 0.0.9 in collectm asap.

Cyril

**Comment by nathanwebb** [comment]
Awesome - thanks for the quick response. I'll update this and have a look at how it goes

**Comment by jhenry82** [comment]
Oh hey, I'm the guy who submitted that issue + patch to node-collectdout. Was coming here to open an issue and ask if you could pull in the new version. I see you're already on it :) Thanks!

**Comment by jhenry82** [comment]
PR #19, update to version 0.0.9 of collectdout

**Comment by jhenry82** [comment]
Thanks for merging! When you're back from holiday, it would be great if you could post a new release with this change.
