### ISSUE TITLE
StatsD

### ISSUE THREAD

**Issue by phillijw** [perfwatcher/collectm#3]
Is there a way to get this sending data to StatsD?

**Comment by ymettier** [comment]
Hello,

Very short answer : yes.

Short answer
Collectm was not designed to send data to anything else than Collectd. The answer is no.

Long answer
Collectm sends data to Collectd and only to Collectd.
But Collectd can send data to StatsD as shortly described here : https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_statsd

So you could deploy Collectd on one server (this is the concentrator). Then deploy many Collectm agents that would send to the concentrator.
With the statsd plugin, the concentrator Collectd would forward the metrics to your StatsD server.
So the final answer is : yes !

Regards,
Yves

**Comment by phillijw** [comment]
Thank you. Exactly what I wanted to know.
