### ISSUE TITLE
Crypto support

### ISSUE THREAD

**Issue by dimrozakis** [perfwatcher/collectm#9]
Collectd's network plugin supports authentication and encryption. We're working on adding crypto support for collectm on https://github.com/perfwatcher/collectm/compare/master...mistio:crypto?w=1 . Is this a feature you'd be interested in merging, once completed? Any thoughts/comments/suggestions on the approach?

(Some notes of mine on collectd's crypto specs: https://gist.github.com/dimrozakis/1b326ac4ee7d3682b7dc)

**Comment by ymettier** [comment]
Hello,

Yes, we are interested in crypto. You need to make it compatible with Collectd of course.

Note that configuration should come in Collectm (as you already started it), but you will also work on node-collectdout (mostly maintained by @feraudet). Don't forget to report your changes on that modules in a PR to https://github.com/astro/node-collectdout.

Regards,
Yves

**Comment by dimrozakis** [comment]
I have opened a PR in astro/node-collectdout about crypto support: https://github.com/astro/node-collectdout/pull/8. Please feel free to review the changes. Once it goes through, I'll open a PR here to complete collectm's crypto support.

**Comment by feraudet** [comment]
Realsed v0.0.8 with your adds is released

**Comment by ymettier** [comment]
Hello,

I created a new branch https://github.com/perfwatcher/collectm/tree/crypto_support with collectdout updated to 0.0.8.

Note : I will probably merge some PR (10, 11, 12, and 13) soon in master. I think there will be no conflict between crypto_support and master branch, but I inform you, in case...

Regards,
Yves

**Comment by ymettier** [comment]
Created a new branch v1.6.0rc with PR #14  (and other commits) in order to test and release a new version 1.6.0 in 1 or 2 weeks.

Please test that branch and report any bugs/regressions since version 1.5.1.

Regards,
Yves
